### ISSUE TITLE
Hash Router > Neue redirect_uri benötigt

### ISSUE THREAD

**Issue by mariohelbing** [cuprit-gbr/daard-frontend#15]
Bisher hatte der Query-Parameter "redirect_uri" folgende Value "http://localhost:3000/login/"
Durch die Verwendung des Hash-Routers muss der neue Wert "http://localhost:3000/#/login/" (mit #) sein.

**Comment by t-book** [comment]
Siehe Slack. Können wir uns für die URL auf http://localhost:3000/!/login/ einigen?

**Comment by mariohelbing** [comment]
Die Url mit dem Ausrufezeichen wird nicht klappen, da wir dann wieder die htaccess benötigen. Bitte trag noch folgende Urls als valide bei Dir ins Backend ein:
http://localhost:3000
http://localhost:3000/

Ich ändere dann dementsprechend meinen Code.
