### ISSUE TITLE
Status der Eingabemaske speichern

### ISSUE THREAD

**Issue by t-book** [cuprit-gbr/daard-frontend#19]
Die Eingabemaske wird überarbeitet um die Auswahl der Knochen und Ihren Änderungen zu speichern. Die Nutzer können hierdurch zwischen den Eingabetabs vor und zurück gehen ohne dass Eingaben verloren gehen. Die Logik gleicht hierbei vorab vorhandene Eingaben mit neuen und gelöschten ab.

**Comment by mariohelbing** [comment]
Ist gefixt und zur Staging-Umgebung gepusht.
