### ISSUE TITLE
Neues GUI-Feld: Select mit Suchen-Feld und Aliases-Feature

### ISSUE THREAD

**Issue by mariohelbing** [cuprit-gbr/daard-frontend#25]
Unter “Disease” soll das “Disease”-Feld ein Dropdown mit Suchenfeld werden. Toni erweitert dafür des Response-Objekt um den Key “aliases” mit einem Array. Hier stehen dann die alternativen Namen unter denen die Krankheit ebenfalls bekannt ist.

**Comment by t-book** [comment]
@mariohelbing 

Das Feld ist hinzugefügt. Siehe

https://dai-gn-test.csgis.de/daard/api/disease-search/?fields=id,name,adults,subadults,aliases&search_age=subadults

```
    {
        "id": 21,
        "adults": true,
        "subadults": true,
        "name": "Osteopetrosis autosomal-dominant type 2",
        "aliases": [
            "Kaluokahina-A",
            "Dorinthis-Kalapeo"
        ]
```

Um das array zu bekommen musst du es bei der Suchanfrage in der `GET` Variable _fields_ vermerken.
?fields=id,name,adults,subadults,**aliases**

**Comment by mariohelbing** [comment]
Ist eingebaut.
