### ISSUE TITLE
NICHT VERGESSEN

### ISSUE THREAD

**Issue by t-book** [cuprit-gbr/daard-frontend#26]
@mariohelbing Da nun einige Zeit vergangen ist. Bitte nicht vergessen nur nach https://github.com/cuprit-gbr/daard-frontend-dev
zu pushen. Welches die staging Instanz füttert. 

(Erwähne es nochmals da wir hier die Issues bearbeiten, nicht das was durcheinander kommt)

**Comment by mariohelbing** [comment]
Kapiert und in meinem Workflow übernommen :)
